valiknet_home:
  path: /{_locale}
  defaults: { _controller: ValiknetMusicBundle:Article:list, _locale: ua }
  requirements:
    _locale: ua|ru|en

valiknet_music:
  resource: "@ValiknetMusicBundle/Resources/config/routing.yml"
  prefix:   /{_locale}
  defaults: { _locale: ua }
  requirements:
    _locale: ua|ru|en
