valiknet_group_list:
  path: /list
  defaults: { _controller: ValiknetMusicBundle:Group:list }

valiknet_group_view:
  path: /{slug}/view
  defaults: { _controller: ValiknetMusicBundle:Group:view }

valiknet_group_clip_list:
  path: /{slug}/clip/list
  defaults: { _controller: ValiknetMusicBundle:Group:listClip }

valiknet_group_clip_view:
  path: /{slug}/clip/{slugClip}/view
  defaults: { _controller: ValiknetMusicBundle:Group:clip }

valiknet_group_release_list:
  path: /{slug}/release/list
  defaults: { _controller: ValiknetMusicBundle:Group:listRelease }

valiknet_group_release_view:
  path: /{slug}/release/{slugRelease}/view
  defaults: { _controller: ValiknetMusicBundle:Group:release }

valiknet_group_player_list:
  path: /{slug}/players
  defaults: { _controller: ValiknetMusicBundle:Group:players }

valiknet_group_contacts:
  path: /{slug}/contacts
  defaults: { _controller: ValiknetMusicBundle:Group:contacts }

valiknet_group_news:
  path: /{slug}/news
  defaults: { _controller: ValiknetMusicBundle:Group:listNews }

valiknet_group_create:
  path: /add
  defaults: { _controller: ValiknetMusicBundle:Group:createGroup }

valiknet_group_update:
  path: /{slug}/update
  defaults: { _controller: ValiknetMusicBundle:Group:updateGroup }

valiknet_group_release_add:
  path: /{slug}/release/add
  defaults: { _controller: ValiknetMusicBundle:Group:addRelease }

valiknet_group_release_update:
  path: /{slug}/release/{slugRelease}/update
  defaults: { _controller: ValiknetMusicBundle:Group:updateRelease }
