valiknet_group_list:
  path: /list
  defaults: { _controller: ValiknetMusicBundle:Group:list }

valiknet_group_view:
  path: /{slug}/view
  defaults: { _controller: ValiknetMusicBundle:Group:view }

valiknet_group_clip_list:
  path: /{slugGroup}/clip/list
  defaults: { _controller: ValiknetMusicBundle:Group:listClip }

valiknet_group_clip_view:
  path: /{slugGroup}/clip/{slugClip}/view
  defaults: { _controller: ValiknetMusicBundle:Group:clip }

valiknet_group_release_list:
  path: /{slugGroup}/release/list
  defaults: { _controller: ValiknetMusicBundle:Group:listRelease }

valiknet_group_release_view:
  path: /{slugGroup}/release/{slugRelease}/view
  defaults: { _controller: ValiknetMusicBundle:Group:release }

valiknet_group_player_list:
  path: /{slug}/players
  defaults: { _controller: ValiknetMusicBundle:Group:players }

valiknet_group_contacts:
  path: /{slug}/contacts
  defaults: { _controller: ValiknetMusicBundle:Group:contacts }

valiknet_group_news:
  path: /{slug}/news
  defaults: { _controller: ValiknetMusicBundle:Group:listNews }
