valiknet_group:
  resource: "@ValiknetMusicBundle/Resources/config/group_routing.yml"
  prefix: /group

valiknet_article:
  resource: "@ValiknetMusicBundle/Resources/config/article_routing.yml"
  prefix: /article

valiknet_user:
  resource: "@ValiknetMusicBundle/Resources/config/user_routing.yml"
  prefix: /user

valiknet_country:
  resource: "@ValiknetMusicBundle/Resources/config/country_routing.yml"
  prefix: /country

valiknet_style:
  resource: "@ValiknetMusicBundle/Resources/config/style_routing.yml"
  prefix: /genre

valiknet_track:
  resource: "@ValiknetMusicBundle/Resources/config/track_routing.yml"
  prefix: /track
