valiknet_user_list:
  path: /list
  defaults: { _controller: ValiknetMusicBundle:User:list }

valiknet_user_view:
  path: /{slug}/view
  defaults: { _controller: ValiknetMusicBundle:User:show }

valiknet_user_groups_list:
  path: /{slug}/groups
  defaults: { _controller: ValiknetMusicBundle:User:listGroups }

valiknet_user_news_list:
  path: /{slug}/news
  defaults: { _controller: ValiknetMusicBundle:User:listNews }

valiknet_user_contacts:
  path: /{slug}/contacts
  defaults: { _controller: ValiknetMusicBundle:User:contacts }

valiknet_user_add:
  path: /add
  defaults: { _controller: ValiknetMusicBundle:User:addUser }

valiknet_user_update:
  path: /{slug}/add
  defaults: { _controller: ValiknetMusicBundle:User:updateUser }

valiknet_user_add_in_group:
  path: /{slug}/addUserInGroup
  defaults: { _controller: ValiknetMusicBundle:User:addUserInGroup }

valiknet_user_update_in_group:
  path: /{slug}/updateUserInGroup/{id}
  defaults: { _controller: ValiknetMusicBundle:User:updateUserInGroup }

valiknet_user_delete_in_group:
  path: /{slug}/deleteUserInGroup/{id}
  defaults: { _controller: ValiknetMusicBundle:User:deleteUserInGroup }
